/*******************************************************************************
 * Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 01:02:05 PM IST 
//


package hydrograph.ui.common.component.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PortSpecification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortSpecification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="port" type="{hydrograph/ui/ComponentConfig}PortInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="numberOfPorts" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="portAlignment" use="required" type="{hydrograph/ui/constant}PortAlignment" />
 *       &lt;attribute name="changePortCountDynamically" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="allowMultipleLinks" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="linkMandatory" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortSpecification", propOrder = {
    "port"
})
public class PortSpecification {

    protected List<PortInfo> port;
    @XmlAttribute(name = "numberOfPorts", required = true)
    protected int numberOfPorts;
    @XmlAttribute(name = "portAlignment", required = true)
    protected PortAlignment portAlignment;
    @XmlAttribute(name = "changePortCountDynamically")
    protected Boolean changePortCountDynamically;
    @XmlAttribute(name = "allowMultipleLinks", required = true)
    protected boolean allowMultipleLinks;
    @XmlAttribute(name = "linkMandatory", required = true)
    protected boolean linkMandatory;

    /**
     * Gets the value of the port property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the port property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortInfo }
     * 
     * 
     */
    public List<PortInfo> getPort() {
        if (port == null) {
            port = new ArrayList<PortInfo>();
        }
        return this.port;
    }

    /**
     * Gets the value of the numberOfPorts property.
     * 
     */
    public int getNumberOfPorts() {
        return numberOfPorts;
    }

    /**
     * Sets the value of the numberOfPorts property.
     * 
     */
    public void setNumberOfPorts(int value) {
        this.numberOfPorts = value;
    }

    /**
     * Gets the value of the portAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link PortAlignment }
     *     
     */
    public PortAlignment getPortAlignment() {
        return portAlignment;
    }

    /**
     * Sets the value of the portAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortAlignment }
     *     
     */
    public void setPortAlignment(PortAlignment value) {
        this.portAlignment = value;
    }

    /**
     * Gets the value of the changePortCountDynamically property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isChangePortCountDynamically() {
        if (changePortCountDynamically == null) {
            return false;
        } else {
            return changePortCountDynamically;
        }
    }

    /**
     * Sets the value of the changePortCountDynamically property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangePortCountDynamically(Boolean value) {
        this.changePortCountDynamically = value;
    }

    /**
     * Gets the value of the allowMultipleLinks property.
     * 
     */
    public boolean isAllowMultipleLinks() {
        return allowMultipleLinks;
    }

    /**
     * Sets the value of the allowMultipleLinks property.
     * 
     */
    public void setAllowMultipleLinks(boolean value) {
        this.allowMultipleLinks = value;
    }

    /**
     * Gets the value of the linkMandatory property.
     * 
     */
    public boolean isLinkMandatory() {
        return linkMandatory;
    }

    /**
     * Sets the value of the linkMandatory property.
     * 
     */
    public void setLinkMandatory(boolean value) {
        this.linkMandatory = value;
    }

}
