/*******************************************************************************
 * Copyright 2017 Capital One Services, LLC and Bitwise, Inc.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.17 at 01:02:05 PM IST 
//


package hydrograph.ui.common.component.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PortInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sequenceOfPort" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="typeOfPort" use="required" type="{hydrograph/ui/constant}PortType" />
 *       &lt;attribute name="portTerminal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="labelOfPort" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortInfo")
public class PortInfo {

    @XmlAttribute(name = "sequenceOfPort", required = true)
    protected int sequenceOfPort;
    @XmlAttribute(name = "typeOfPort", required = true)
    protected PortType typeOfPort;
    @XmlAttribute(name = "portTerminal", required = true)
    protected String portTerminal;
    @XmlAttribute(name = "labelOfPort", required = true)
    protected String labelOfPort;

    /**
     * Gets the value of the sequenceOfPort property.
     * 
     */
    public int getSequenceOfPort() {
        return sequenceOfPort;
    }

    /**
     * Sets the value of the sequenceOfPort property.
     * 
     */
    public void setSequenceOfPort(int value) {
        this.sequenceOfPort = value;
    }

    /**
     * Gets the value of the typeOfPort property.
     * 
     * @return
     *     possible object is
     *     {@link PortType }
     *     
     */
    public PortType getTypeOfPort() {
        return typeOfPort;
    }

    /**
     * Sets the value of the typeOfPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortType }
     *     
     */
    public void setTypeOfPort(PortType value) {
        this.typeOfPort = value;
    }

    /**
     * Gets the value of the portTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortTerminal() {
        return portTerminal;
    }

    /**
     * Sets the value of the portTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortTerminal(String value) {
        this.portTerminal = value;
    }

    /**
     * Gets the value of the labelOfPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelOfPort() {
        return labelOfPort;
    }

    /**
     * Sets the value of the labelOfPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelOfPort(String value) {
        this.labelOfPort = value;
    }

}
